# Generated by Django 5.2.17 on 2026-09-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technology & Coding'), ('STUDY', 'Study & Education'), ('SPORTS', 'Sports & Fitness'), ('FUNNY', 'Humor & Memes'), ('GENERAL', 'General Community')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
