# Generated by Django 5.2.17 on 2026-09-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_category_alter_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='avatar_emoji',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
