# Generated by Django 5.2.17 on 2026-09-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_avatar_emoji_tenant_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='category',
            field=models.CharField(default='General Community', max_length=100),
        ),
    ]
